
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Hot_Pot_Restaurant_Management_System.Models.Entities
{

using System;
    using System.Collections.Generic;
    
public partial class BillDetails
{

    public string ID { get; set; }

    public string DishName { get; set; }

    public double Amount { get; set; }

    public string OrderID { get; set; }

    public Nullable<int> WarehouseID { get; set; }

    public string POID { get; set; }

}

}
