
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Hot_Pot_Restaurant_Management_System.Models.Entities
{

using System;
    using System.Collections.Generic;
    
public partial class Dish
{

    public int ID { get; set; }

    public int ShortID { get; set; }

    public string Name { get; set; }

    public string ShortName { get; set; }

    public int CategoryID { get; set; }

    public decimal Price { get; set; }

    public string Unit { get; set; }

    public string Image { get; set; }

    public string Description { get; set; }

    public bool PriceEditable { get; set; }

    public bool InventoryControl { get; set; }

    public Nullable<double> UnitConversion { get; set; }

}

}
