

//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Hot_Pot_Restaurant_Management_System.Models.Entities
{

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;


public partial class FrontDeskEntities : DbContext
{
    public FrontDeskEntities()
        : base("name=FrontDeskEntities")
    {

    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }


    public DbSet<Dish> Dish { get; set; }

    public DbSet<ServingTable> ServingTable { get; set; }

    public DbSet<BillDetails> BillDetails { get; set; }

    public DbSet<Discount> Discount { get; set; }

    public DbSet<Bill> Bill { get; set; }

    public DbSet<VBill> VBill { get; set; }

    public DbSet<Member> Member { get; set; }

}

}

