
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Hot_Pot_Restaurant_Management_System.Models.Entities
{

using System;
    using System.Collections.Generic;
    
public partial class Member
{

    public string ID { get; set; }

    public string Name { get; set; }

    public string Tele { get; set; }

    public int Point { get; set; }

}

}
