
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Hot_Pot_Restaurant_Management_System.Models.Entities
{

using System;
    using System.Collections.Generic;
    
public partial class MReportDetails
{

    public string ID { get; set; }

    public string ProductName { get; set; }

    public string OrderID { get; set; }

    public decimal PurchasePrice { get; set; }

    public double PurchaseAmount { get; set; }

    public decimal PurchaseTotalPrice { get; set; }

    public double MRequisitionAmount { get; set; }

    public double MReturnAmount { get; set; }

    public decimal CreditPrice { get; set; }

    public double CreditAmount { get; set; }

    public decimal CreditTotalPrice { get; set; }

    public decimal SListPrice { get; set; }

    public double SListAmount { get; set; }

    public decimal SListTotalPrice { get; set; }

    public decimal MRequisitionPrice { get; set; }

    public decimal MRequisitionTotalPrice { get; set; }

    public decimal MReturnPrice { get; set; }

    public decimal MReturnTotalPrice { get; set; }

    public decimal BillPrice { get; set; }

    public double BillAmount { get; set; }

    public decimal BillTotalPrice { get; set; }

}

}
