
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Hot_Pot_Restaurant_Management_System.Models.Entities
{

using System;
    using System.Collections.Generic;
    
public partial class StocktakingList
{

    public string ID { get; set; }

    public string WarehouseName { get; set; }

    public int OperatorID { get; set; }

    public string OperatorName { get; set; }

    public int UserID { get; set; }

    public string UserName { get; set; }

    public System.DateTime Date { get; set; }

    public string Remark { get; set; }

}

}
