
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Hot_Pot_Restaurant_Management_System.Models.Entities
{

using System;
    using System.Collections.Generic;
    
public partial class VBill
{

    public string BillID { get; set; }

    public int TableID { get; set; }

    public System.DateTime Date { get; set; }

    public int CustomerCount { get; set; }

    public int TimePeriod { get; set; }

    public decimal TotalCost { get; set; }

    public Nullable<int> Discount { get; set; }

    public string DiscountType { get; set; }

    public decimal ExactCost { get; set; }

    public string Remark { get; set; }

    public int UserID { get; set; }

    public string UserName { get; set; }

    public string DetailsID { get; set; }

    public string DishName { get; set; }

    public double Amount { get; set; }

    public string MemberID { get; set; }

    public decimal ReceivedMoney { get; set; }

    public decimal Change { get; set; }

}

}
