
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Hot_Pot_Restaurant_Management_System.Models.Entities
{

using System;
    using System.Collections.Generic;
    
public partial class VInventoryList
{

    public string POID { get; set; }

    public int ProductID { get; set; }

    public int ProductShortID { get; set; }

    public string ProductName { get; set; }

    public string ProductShortName { get; set; }

    public int WarehouseID { get; set; }

    public int WarehouseShortID { get; set; }

    public string WarehouseName { get; set; }

    public double Amount { get; set; }

    public string Unit { get; set; }

}

}
