

//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Hot_Pot_Restaurant_Management_System.Models.Entities
{

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;


public partial class WarehouseEntities : DbContext
{
    public WarehouseEntities()
        : base("name=WarehouseEntities")
    {

    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }


    public DbSet<Category> Category { get; set; }

    public DbSet<CreditOrder> CreditOrder { get; set; }

    public DbSet<MaterialsRequisition> MaterialsRequisition { get; set; }

    public DbSet<MaterialsReturnOrder> MaterialsReturnOrder { get; set; }

    public DbSet<PurchaseOrder> PurchaseOrder { get; set; }

    public DbSet<StocktakingList> StocktakingList { get; set; }

    public DbSet<TransferOrder> TransferOrder { get; set; }

    public DbSet<Warehouse> Warehouse { get; set; }

    public DbSet<Product> Product { get; set; }

    public DbSet<CODetails> CODetails { get; set; }

    public DbSet<InventoryList> InventoryList { get; set; }

    public DbSet<MRDetails> MRDetails { get; set; }

    public DbSet<MRODetails> MRODetails { get; set; }

    public DbSet<PODetails> PODetails { get; set; }

    public DbSet<SLDetails> SLDetails { get; set; }

    public DbSet<TODetails> TODetails { get; set; }

    public DbSet<VInventoryList> VInventoryList { get; set; }

}

}

